version: '3.8'

services:
  octomap-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ci
    volumes:
      - ..:/home/octomap
      - /home/octomap/__pycache__
    working_dir: /home/octomap
    command: /bin/bash
    environment:
      - PYTHONPATH=/home/octomap
